import React from 'react'
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer'
import { format } from 'date-fns'

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica' },
  title: { fontSize: 20, fontWeight: 'bold', marginBottom: 20 },
  meta: { marginBottom: 30 },
  table: { width: '100%' },
  tableHeader: {
    flexDirection: 'row',
    borderBottom: '1px solid #000',
    paddingBottom: 5,
    marginBottom: 5,
    fontWeight: 'bold',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: '1px solid #eee',
    paddingVertical: 8,
    minHeight: 30,
  },
  colOrder: { width: '20%' },
  colCustomer: { width: '25%' },
  colItems: { width: '40%' },
  colCondition: { width: '15%' },
  itemRow: { marginBottom: 2 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#666' }
})

interface ReturnsReportProps {
  date: Date
  companyName: string
  returns: Array<{
    orderNumber: string
    customerName: string | null
    scannedAt: Date
    items: Array<{
      skuOrProductName: string
      quantity: number
      condition: string
    }>
  }>
}

export const ReturnsReportDocument: React.FC<ReturnsReportProps> = ({ date, companyName, returns }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>Daily Returns Report</Text>
      
      <View style={styles.meta}>
        <Text>Company: {companyName}</Text>
        <Text>Date: {format(date, 'dd.MM.yyyy')}</Text>
        <Text>Total Returns: {returns.length}</Text>
      </View>

      <View style={styles.table}>
        <View style={styles.tableHeader}>
          <Text style={styles.colOrder}>Order No.</Text>
          <Text style={styles.colCustomer}>Customer</Text>
          <Text style={styles.colItems}>Items</Text>
          <Text style={styles.colCondition}>Condition</Text>
        </View>

        {returns.map((entry, idx) => (
          <View key={idx} style={styles.tableRow} wrap={false}>
            <Text style={styles.colOrder}>{entry.orderNumber}</Text>
            <Text style={styles.colCustomer}>{entry.customerName || 'N/A'}</Text>
            
            <View style={styles.colItems}>
              {entry.items.map((item, i) => (
                <Text key={i} style={styles.itemRow}>
                  {item.quantity}x {item.skuOrProductName}
                </Text>
              ))}
            </View>

            <View style={styles.colCondition}>
              {entry.items.map((item, i) => (
                <Text key={i} style={styles.itemRow}>
                  {item.condition}
                </Text>
              ))}
            </View>
          </View>
        ))}
      </View>

      <Text style={styles.footer} fixed>
        Generated by TheOmniStack on {format(new Date(), 'dd.MM.yyyy HH:mm')}
      </Text>
    </Page>
  </Document>
)
