export const EU_COUNTRIES = [
  { code: 'AT', name: 'Österreich', standardRate: 20, reducedRate: 10 },
  { code: 'BE', name: 'Belgien', standardRate: 21, reducedRate: 12 },
  { code: 'BG', name: 'Bulgarien', standardRate: 20, reducedRate: 9 },
  { code: 'CY', name: 'Zypern', standardRate: 19, reducedRate: 9 },
  { code: 'CZ', name: 'Tschechien', standardRate: 21, reducedRate: 12 },
  { code: 'DE', name: 'Deutschland', standardRate: 19, reducedRate: 7 },
  { code: 'DK', name: 'Dänemark', standardRate: 25, reducedRate: 25 }, // No reduced rate
  { code: 'EE', name: 'Estland', standardRate: 22, reducedRate: 9 },
  { code: 'ES', name: 'Spanien', standardRate: 21, reducedRate: 10 },
  { code: 'FI', name: 'Finnland', standardRate: 24, reducedRate: 14 },
  { code: 'FR', name: 'Frankreich', standardRate: 20, reducedRate: 10 },
  { code: 'GR', name: 'Griechenland', standardRate: 24, reducedRate: 13 },
  { code: 'HR', name: 'Kroatien', standardRate: 25, reducedRate: 13 },
  { code: 'HU', name: 'Ungarn', standardRate: 27, reducedRate: 18 },
  { code: 'IE', name: 'Irland', standardRate: 23, reducedRate: 13.5 },
  { code: 'IT', name: 'Italien', standardRate: 22, reducedRate: 10 },
  { code: 'LT', name: 'Litauen', standardRate: 21, reducedRate: 9 },
  { code: 'LU', name: 'Luxemburg', standardRate: 17, reducedRate: 8 },
  { code: 'LV', name: 'Lettland', standardRate: 21, reducedRate: 12 },
  { code: 'MT', name: 'Malta', standardRate: 18, reducedRate: 7 },
  { code: 'NL', name: 'Niederlande', standardRate: 21, reducedRate: 9 },
  { code: 'PL', name: 'Polen', standardRate: 23, reducedRate: 8 },
  { code: 'PT', name: 'Portugal', standardRate: 23, reducedRate: 13 },
  { code: 'RO', name: 'Rumänien', standardRate: 19, reducedRate: 9 },
  { code: 'SE', name: 'Schweden', standardRate: 25, reducedRate: 12 },
  { code: 'SI', name: 'Slowenien', standardRate: 22, reducedRate: 9.5 },
  { code: 'SK', name: 'Slowakei', standardRate: 20, reducedRate: 10 },
]

export const WORLD_COUNTRIES = [
  ...EU_COUNTRIES.map(c => ({ code: c.code, name: c.name })),
  { code: 'CH', name: 'Schweiz' },
  { code: 'GB', name: 'Vereinigtes Königreich' },
  { code: 'US', name: 'Vereinigte Staaten' },
  { code: 'CA', name: 'Kanada' },
  { code: 'AU', name: 'Australien' },
  { code: 'JP', name: 'Japan' },
  { code: 'CN', name: 'China' },
  { code: 'IN', name: 'Indien' },
  { code: 'BR', name: 'Brasilien' },
  { code: 'MX', name: 'Mexiko' },
  { code: 'NO', name: 'Norwegen' },
  { code: 'TR', name: 'Türkei' },
  { code: 'AE', name: 'Verreinigte Arabische Emirate' },
  { code: 'SG', name: 'Singapur' },
  { code: 'HK', name: 'Hongkong' },
  { code: 'IL', name: 'Israel' },
  { code: 'ZA', name: 'Südafrika' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'IS', name: 'Island' },
  { code: 'MC', name: 'Monaco' },
  { code: 'NZ', name: 'Neuseeland' },
  { code: 'KR', name: 'Südkorea' },
  { code: 'TH', name: 'Thailand' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'ID', name: 'Indonesien' },
].sort((a, b) => a.name.localeCompare(b.name))

export function get2LetterCountryCode(country: string | null | undefined): string {
  if (!country) return 'DE';
  const clean = country.trim().toUpperCase();
  if (clean.length === 2) return clean;

  const mapping: Record<string, string> = {
    DEU: 'DE',
    AUT: 'AT',
    FRA: 'FR',
    ITA: 'IT',
    ESP: 'ES',
    CZE: 'CZ',
    BEL: 'BE',
    NLD: 'NL',
    LUX: 'LU',
    POL: 'PL',
    DNK: 'DK',
    SWE: 'SE',
    FIN: 'FI',
    IRL: 'IE',
    PRT: 'PT',
    GRC: 'GR',
    HRV: 'HR',
    BGR: 'BG',
    ROU: 'RO',
    HUN: 'HU',
    SVK: 'SK',
    SVN: 'SI',
    EST: 'EE',
    LVA: 'LV',
    LTU: 'LT',
    MLT: 'MT',
    CYP: 'CY',
    GBR: 'GB',
    USA: 'US',
    CAN: 'CA',
    CHE: 'CH',
    AUS: 'AU',
    JPN: 'JP',
    CHN: 'CN',
    IND: 'IN',
    BRA: 'BR',
    MEX: 'MX',
    NOR: 'NO',
    TUR: 'TR',
    ARE: 'AE',
    SGP: 'SG',
    HKG: 'HK',
    ISR: 'IL',
    ZAF: 'ZA',
    LIE: 'LI',
    ISL: 'IS',
    MCO: 'MC',
    NZL: 'NZ',
    KOR: 'KR',
    THA: 'TH',
    VNM: 'VN',
    MYS: 'MY',
    IDN: 'ID',
  };
  const engMapping: Record<string, string> = {
    'AUSTRIA': 'AT',
    'BELGIUM': 'BE',
    'BULGARIA': 'BG',
    'CYPRUS': 'CY',
    'CZECHIA': 'CZ',
    'CZECH REPUBLIC': 'CZ',
    'GERMANY': 'DE',
    'DENMARK': 'DK',
    'ESTONIA': 'EE',
    'SPAIN': 'ES',
    'FINLAND': 'FI',
    'FRANCE': 'FR',
    'GREECE': 'GR',
    'CROATIA': 'HR',
    'HUNGARY': 'HU',
    'IRELAND': 'IE',
    'ITALY': 'IT',
    'LITHUANIA': 'LT',
    'LUXEMBOURG': 'LU',
    'LATVIA': 'LV',
    'MALTA': 'MT',
    'NETHERLANDS': 'NL',
    'POLAND': 'PL',
    'PORTUGAL': 'PT',
    'ROMANIA': 'RO',
    'SWEDEN': 'SE',
    'SLOVENIA': 'SI',
    'SLOVAKIA': 'SK',
    'SWITZERLAND': 'CH',
    'UNITED KINGDOM': 'GB',
    'GREAT BRITAIN': 'GB',
    'UNITED STATES': 'US',
    'USA': 'US',
    'CANADA': 'CA',
    'AUSTRALIA': 'AU',
    'JAPAN': 'JP',
    'CHINA': 'CN',
    'INDIA': 'IN',
    'BRAZIL': 'BR',
    'MEXICO': 'MX',
    'NORWAY': 'NO',
    'TURKEY': 'TR',
    'SINGAPORE': 'SG',
    'HONG KONG': 'HK',
    'ISRAEL': 'IL',
    'SOUTH AFRICA': 'ZA',
    'LIECHTENSTEIN': 'LI',
    'ICELAND': 'IS',
    'MONACO': 'MC',
    'NEW ZEALAND': 'NZ',
    'SOUTH KOREA': 'KR',
    'THAILAND': 'TH',
    'VIETNAM': 'VN',
    'MALAYSIA': 'MY',
    'INDONESIA': 'ID'
  };

  if (mapping[clean]) return mapping[clean];
  if (engMapping[clean]) return engMapping[clean];

  // Try to find by name if it wasn't a 3-letter code
  const foundByName = WORLD_COUNTRIES.find(c => c.name.toUpperCase() === clean);
  if (foundByName) return foundByName.code;

  return clean;
}

